In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

In [ ]:
from sklearn.datasets import load_wine
data = load_wine()
X = data.data
y = data.target

In [ ]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

y_cat = to_categorical(y)

X_train, X_test, y_train, y_test = train_test_split(X, y_cat, test_size=0.2, random_state=42)

In [ ]:
model = Sequential()
model.add(Dense(16, activation='sigmoid', input_shape=(X.shape[1],)))
model.add(Dense(24, activation='sigmoid'))
model.add(Dense(10, activation='sigmoid'))
model.add(Dense(y_cat.shape[1], activation='softmax'))

model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=260, batch_size=64, verbose=1)

model.save("wine_ann_model.h5")

Epoch 1/260


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.3284 - loss: 1.1058
Epoch 2/260
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.3030 - loss: 1.0982
Epoch 3/260
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.3088 - loss: 1.0872 
Epoch 4/260
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.3186 - loss: 1.0809
Epoch 5/260
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.3217 - loss: 1.0789
Epoch 6/260
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.3127 - loss: 1.0738 
Epoch 7/260
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.3272 - loss: 1.0670
Epoch 8/260
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.3984 - loss: 1.0653
Epoch 9/260
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4038 - loss: 1.0603
Epoch 10/260
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.4019 - loss: 1.0597 
Epoch 11/260
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.4038 - loss: 1.0545
Epoch 12/260
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.4175 - loss: 1.047

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

model = load_model("wine_ann_model.h5")

y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)
y_true = np.argmax(y_test, axis=1)

print("Confusion Matrix:")
print(confusion_matrix(y_true, y_pred))

print("\nClassification Report:")
print(classification_report(y_true, y_pred))


1/2 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
Confusion Matrix:
[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         8

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36



In [ ]:
model = load_model("wine_ann_model.h5")

sample = X_test[0].reshape(1, -1)
prediction = np.argmax(model.predict(sample))
print(f"Predicted wine class: {prediction}")


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
Predicted wine class: 0
